---
title: "Chapter 8"
author: "BPR"
date: "8/23/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
{         # Put the cursor on this line, and run it; because
          #  of the curly braces, all the code within
          #  the braces will be run.
  c("changepoint",    # Some basic changepoint routines
    "changepoint.np", # More changepoint routines
    "data.table",     # fread() for FAST and flexible data input
    "dplyr",          # Data wrangling
#    "dtplyr",         # For faster data wrangling with tidyverse structure
#    "goftest",        # CVM test
    "here",           # To assist with folder structure
    "knitr",          # Better table printing
#    "MASS",           # For fitting distributions
#    "poweRlaw") ->    # To fit power law data; MASS::fitdistr() can't
    "tseriesChaos") ->
  package_names

  for (package_name in package_names) {
    if (!is.element(package_name, installed.packages()[, 1])) {
      install.packages(package_name, repos = "http://lib.stat.cmu.edu/R/CRAN")
    }
    library(package_name,
            character.only = TRUE,
            quietly = TRUE,
            verbose = FALSE
    )
  }
  rm(list = c("package_names", "package_name"))
}

# Reprodcibility
set_here()      # This helps with folder structure when shifting computers

# Usually, seeds for random number generation would be set here. They are, for
#  pedagogical reasons, set with each snippet of code.

# Stuff I prefer
options(show.signif.stars = FALSE) # Do not show significance stars! Showing
                                   #  significance stars encourages the
                                   #  conflation of significant and effect
                                   #  size.
options(digits = 3)                # Round displays to 3 digits
```

```{r F8.1}
sim.cont(lorenz.syst,             # Simulate the Lorenz system...
         start.time = 0,          #  starting from time 0...
         end.time = 10000,        #  going to time 10,000...
         dt = 0.05,               #  computing every 0.05 time intervals...
         parms = c(10, 28, -8/3), #  with these parameters...
         start.x = c(5,5,5),      #  and these starting values.
         obs.fun = function(x){list(x)}) -> lorenz_ts # Just observe the values

unlist(lorenz_ts) -> temp_ts                        # Change a list to a vector
unname(temp_ts[names(temp_ts) == "1"]) -> lorenz.x  # Just the x-component (1)
plot(lorenz.x[1:1000], type = 'l',                  # Plot 1000 points
     main = "x-component of Lorenz system",         # Title
     xlab = "index",                                # x-axis label
     ylab = "Lorenz - x")                           # y-axis label
```


```{r F8.2}
sim.cont(lorenz.syst,             # Simulate the Lorenz system...
         start.time = 0,          #  starting from time 0...
         end.time = 10000,        #  going to time 10,000...
         dt = 0.01,               #  computing every 0.01 time intervals...
         parms = c(10, 28, -8/3), #  with these parameters...
         start.x = c(5,5,5),      #  and these starting values.
         obs.fun = function(x){list(x)}) -> lorenz_ts # Just observe the values


unlist(lorenz_ts) -> temp_ts                        # List to vector
unname(temp_ts[names(temp_ts) == "1"]) -> lorenz.x  # "1" for the x-values
unname(temp_ts[names(temp_ts) == "2"]) -> lorenz.y  # "2" for the y-values

plot(lorenz.x[1:10000], lorenz.y[1:10000], # state-space plot 
     type = 'l',                           # lines
     main = "Lorenz butterfly",            # graph title
     xlab = "Lorenz - x",                  # x-axis label
     ylab = "Lorenz - y",                  # y-axis label
     sub = "Projected onto x-y plane")     # sub-title
```


```{r F8.3}
load(here("Data/RJBphase1.RData"))           # Load RJB data example data
load(here("Data/RJBphase2.RData"))           # Load RJB data example data
transitionNetwork(phase1)[[1]] -> network1   # First Markov matrix
transitionNetwork(phase2)[[1]] -> network2   # Second Markov matrix
qgraph(network1)                             # 8.3(a)
qgraph(network2)                             # 8.3(b)
```


```{r F8.4}
load(here("Data/walking1.RData"))
plot(walking1.x, walking1.y,
     type = 'l',
     main = "Knee and Ankle angles for four steps",
     xlab = "Knee angle",
     ylab = "Angle angle")
```


```{r F8.5}
load(here("Data/RJBphase1.RData"))
paste(phase1, sep="1", collapse = "")
```


```{r CS8.1}
data(Nile)          # Built-in dataset
str(Nile)           # Note that it starts in 1871
cpt.mean(Nile) -> Nile_cpt
cpts(Nile_cpt)      # Change point at 28th point, which is 1898
```


```{r F8.6}
plot(Nile_cpt,
     ylab = "Annual Flow (100 billion liters)",
     main = "Nile annual water flow")
```


```{r CS8.2}
data("wave.c44137")
cpt.mean(wave.c44137)
cpt.mean(wave.c44137[1:50000])

mean(wave.c44137[1:61036])
mean(wave.c44137[61036:63651])

```


```{r F8.7}
data("wave.c44137")

# Plot one value per day
plot(wave.c44137[which(1:length(wave.c44137) %% 24 == 0)],
     type = 'l',
     ylab = "Buoy height")
```



```{r F8.8}
read.csv(file = "https://raw.githubusercontent.com/philippberens/lifespan/master/lifeexpectancy.csv",
         header = TRUE) -> lifespans
{
  plot(lifespans$Year, lifespans$Age,
       pch = 16,
       cex = 0.7,
       col = base::ifelse(lifespans$Year < 1998,
                          "blue", "green"))
  # Add lines of best fit
}
```


```{r CS8.9}
read.csv(file = "https://raw.githubusercontent.com/philippberens/lifespan/master/lifeexpectancy.csv",
         header = TRUE) -> lifespans
rbind(lifespans,
      read.csv(file = "https://raw.githubusercontent.com/philippberens/lifespan/master/extended_data_6",
               header = TRUE)) -> lifespans

{
  plot(lifespans$Year, lifespans$Age,
       pch = 16,
       cex = 0.7,
       col = base::ifelse(lifespans$Year < 1998,
                          "blue", "green"))
  # Add lines of best fit
}
```


```{r CS8.3}

```




```{r F8.}
rnorm(200, 2, .5) -> before
rnorm(200, 4, .5) -> after
c(before, after) -> change_data
plot(change_data,
     type = 'l',
     main = "Data created for changepoints",
     xlab = "index",
     ylab = "data value")
cpt.mean(change_data)
```



```{r}
rnorm(20, 5, 2) -> y1
rnorm(20, 3, 1) -> y2
data.frame("Group" = c(rep("A",20), rep("B", 20)),
           "Value" = c(y1, y2)) -> data1
lm(Value ~ Group, data = data1) -> d_lm

aov(Value ~ Group, data1) -> d_a

summary(d_lm)
summary(d_a)

```



```{r F8.3}
# Data showing an obvious cpt.mean() - plot with lines
# Data showing an obvious cpt.var() - plot with variance boundaries
# Data showing an obvious slope change - plot with lines
# Data showing a relatively obvious kurtosis change - plot...follow up plot showing kurtosis differences at different times

```


```{r lifespan}
read.csv(file = 
           "https://raw.githubusercontent.com/philippberens/lifespan/master/GRG_data.csv",
         skip = 1,
         header = FALSE,
         stringsAsFactors = FALSE,
         sep = ';') -> dum1
dum1[,-1] -> dum1
colnames(grg) -> colnames(dum1)
as.POSIXct.Date(dum1[5,]) -> dum1$deathDatePX

plot(grg$deathDatePX, dum1$`Total Days`, cex = 0.5)
hist(dum1$`Total Days`, breaks = 50)
```



```{r F8.19}
# numbers (final learning) plotted on a grid of rH vs. rL

```


```{r F8.20}
# 3-d plot of something for this
```




0.1 -> x_min    # Put the minimum value of the range here
10 -> x_max     # Put the maximum value of the range here
10 -> num_val   # Put the number of values to try here
(x_max/x_min) ^ (1/(num_val-1)) -> p
print(x_min)
for(i in 1:9) {
  print(x_min * (p ^ i))
}


