---
title: "Chapter 9"
author: "BPR"
date: "1/19/2021"
output: word_document
---

```{r setup}

```

Prep the data for Code Snippet 9.1. Because these data needed some processes, but were not mine, I left the original owner's information in this file.
```{r Prep, include=FALSE, eval=FALSE}
fread("http://www.stat.cmu.edu/~hseltman/309/Book/data/MMvideo.txt") -> video
as.factor(video$agegrp) -> video$AgeGroup
NULL -> attr(video, ".internal.selfref")
write.csv(video,
          file = here("Data/video.csv"))
```
These data were then stored on the book's website

```{r CS9.1}
#fread()
hist(video$score,
     breaks = 30)
ad.test(video$score, "pnorm")

```



Data from van der Haas & Molenaar (1992). Will be inexact because I'm reading graphs. (However, package:metDigitise (Github, "daniel1noble/metaDigitise") can do this, it appears.)
```{r}
c(0,2,4,6,8,10,12) -> scores
# Assume 100 children at each age
c(66, 25, 9, 0, 0, 0, 0) -> age4
c(52, 38, 7, 1, 0, 0, 2) -> age4.5
c(66, 24, 9, 0, 1, 0, 0) -> age5
c(52, 21, 10, 3, 0, 4, 10) -> age5.5
c(41, 20, 9, 8, 8, 7, 7) -> age6
c(21, 3, 13, 8, 18, 6, 31) -> age6.5
c(12, 25, 9, 0, 0, 0, 41) -> age7
c(2, 2, 0, 0, 4, 7, 85) -> age7.5
```

